data "google_compute_global_address" "quest_webapp_ip" {
  name = "quest-webapp-ip"
  project = var.project_id
}

resource "google_compute_ssl_certificate" "quest_webapp_cert" {
    name        = "quest-webapp-self-signed-cert"
    project = var.project_id
    # these files should be created in the same directory as this Terraform file
    # and can be generated by calling sh generate_cert.sh
    private_key = try(file("${path.module}/selfsigned.key"), "")
    certificate = try(file("${path.module}/selfsigned.crt"), "")
}

resource "google_compute_target_https_proxy" "quest_webapp_https_proxy" {
  name             = "quest-webapp-https-proxy"
  project = var.project_id
  url_map          = var.url_map_id
  ssl_certificates = [google_compute_ssl_certificate.quest_webapp_cert.id]
}

resource "google_compute_global_forwarding_rule" "quest_webapp_https_forwarding_rule" {
  name                  = "quest-webapp-https-forwarding-rule"
  project = var.project_id
  target                = google_compute_target_https_proxy.quest_webapp_https_proxy.id
  port_range            = "443"
  ip_protocol           = "TCP"
  load_balancing_scheme = "EXTERNAL"
  ip_address            = data.google_compute_global_address.quest_webapp_ip.address
}